import LeagueNav from "@/components/LeagueNav";
import PageHeader from "@/components/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { formatPoints, statusLabel } from "@/lib/league";
import { ShieldCheck } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function Commissioner() {
  const { user } = useAuth();
  const utils = trpc.useUtils();
  const { data: overview } = trpc.league.overview.useQuery();
  const { data, isLoading, error } = trpc.admin.controlPanel.useQuery(undefined, { enabled: user?.role === "admin" });
  const [auctionPlayerId, setAuctionPlayerId] = useState(""); const [auctionStatus, setAuctionStatus] = useState("auction_in_progress"); const [auctionManagerId, setAuctionManagerId] = useState(""); const [auctionPrice, setAuctionPrice] = useState(""); const [auctionNote, setAuctionNote] = useState("");
  const [homeManagerId, setHomeManagerId] = useState(""); const [awayManagerId, setAwayManagerId] = useState(""); const [fixtureDate, setFixtureDate] = useState(""); const [venue, setVenue] = useState("");
  const [arishUserId, setArishUserId] = useState(""); const [memberForLink, setMemberForLink] = useState(""); const [accountForLink, setAccountForLink] = useState("");
  const [rosterPlayerId, setRosterPlayerId] = useState(""); const [reassignmentManagerId, setReassignmentManagerId] = useState(""); const [rosterReason, setRosterReason] = useState("");
  const [adjustmentManagerId, setAdjustmentManagerId] = useState(""); const [adjustmentAmount, setAdjustmentAmount] = useState(""); const [adjustmentReason, setAdjustmentReason] = useState("");
  const recordAuction = trpc.admin.recordAuction.useMutation({ onSuccess: () => { toast.success("Auction record saved."); utils.admin.controlPanel.invalidate(); utils.league.invalidate(); }, onError: error => toast.error(error.message) });
  const saveFixture = trpc.admin.saveFixture.useMutation({ onSuccess: () => { toast.success("Fixture saved."); utils.admin.controlPanel.invalidate(); utils.league.fixtures.invalidate(); }, onError: error => toast.error(error.message) });
  const marketApproval = trpc.admin.setMarketApproval.useMutation({ onSuccess: () => { toast.success("Market approval updated."); utils.league.overview.invalidate(); }, onError: error => toast.error(error.message) });
  const assignSeat = trpc.admin.assignAdminSeat.useMutation({ onSuccess: () => { toast.success("Administrator seat assigned."); utils.admin.controlPanel.invalidate(); }, onError: error => toast.error(error.message) });
  const linkAccount = trpc.admin.linkAccount.useMutation({ onSuccess: () => { toast.success("Account linked to league member."); utils.admin.controlPanel.invalidate(); }, onError: error => toast.error(error.message) });
  const reassignRoster = trpc.admin.reassignRosterOwnership.useMutation({ onSuccess: () => { toast.success("Roster ownership reassigned and audited."); utils.admin.controlPanel.invalidate(); utils.league.invalidate(); }, onError: error => toast.error(error.message) });
  const adjustBalance = trpc.admin.recordBalanceAdjustment.useMutation({ onSuccess: () => { toast.success("Balance adjustment recorded and audited."); utils.admin.controlPanel.invalidate(); utils.league.invalidate(); }, onError: error => toast.error(error.message) });
  if (user?.role !== "admin") return <LeagueNav><div className="mx-auto max-w-2xl py-12"><div className="league-card p-8"><ShieldCheck className="size-7 text-[#C2871F]" /><h1 className="mt-4 font-display text-3xl text-[#153126]">Commissioner access only</h1><p className="mt-3 text-sm leading-6 text-slate-600">The owner or Arish must assign this account to an administrator seat before commissioner controls become available.</p></div></div></LeagueNav>;
  const playerRows = data?.directory.filter(member => member.leagueRole === "player") ?? [];
  const managers = data?.rosters.map(entry => entry.manager) ?? [];
  const rosteredPlayers = data?.rosters.flatMap(entry => entry.players.map(player => ({ ...player, teamName: entry.manager.teamName }))) ?? [];
  const currentSeat = overview?.identity.adminSeat;
  return <LeagueNav><div className="mx-auto max-w-7xl space-y-7"><PageHeader eyebrow="Commissioner desk" title="League administration" description="Record ongoing auction outcomes, maintain rosters and fixtures, link secure member accounts, and control the market safeguard." />
    {isLoading ? <p className="text-sm text-slate-500">Loading commissioner records…</p> : error ? <p className="text-sm text-red-600">{error.message}</p> : <>
      <section className="grid gap-5 lg:grid-cols-2"><article className="league-card p-6"><div className="flex items-start justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[0.19em] text-[#C2871F]">Two-admin safeguard</p><h2 className="mt-1 font-display text-2xl text-[#153126]">Transfer market approval</h2></div><Badge className={overview?.summary.market.isOpen ? "bg-emerald-100 text-emerald-800 hover:bg-emerald-100" : "bg-[#153126] text-white hover:bg-[#153126]"}>{overview?.summary.market.isOpen ? "Open" : "Closed"}</Badge></div><p className="mt-3 text-sm leading-6 text-slate-600">Both the owner and Arish must independently approve opening the market. Removing either approval closes it immediately.</p><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div className="league-panel p-3"><p className="text-xs text-slate-500">Owner</p><p className="mt-1 font-semibold text-[#153126]">{overview?.summary.market.ownerEnabled ? "Approved" : "Waiting"}</p></div><div className="league-panel p-3"><p className="text-xs text-slate-500">Arish</p><p className="mt-1 font-semibold text-[#153126]">{overview?.summary.market.arishEnabled ? "Approved" : "Waiting"}</p></div></div>{currentSeat ? <Button onClick={() => marketApproval.mutate({ enabled: currentSeat === "owner" ? !overview?.summary.market.ownerEnabled : !overview?.summary.market.arishEnabled })} disabled={marketApproval.isPending} className="mt-5 bg-[#1B4332] hover:bg-[#153126]">{(currentSeat === "owner" ? overview?.summary.market.ownerEnabled : overview?.summary.market.arishEnabled) ? "Remove my approval" : "Approve market opening"}</Button> : <p className="mt-5 text-sm text-[#B47711]">Assign this account to the owner or Arish seat to control market approval.</p>}</article>
        <article className="league-card p-6"><p className="text-[11px] font-bold uppercase tracking-[0.19em] text-[#C2871F]">Secure accounts</p><h2 className="mt-1 font-display text-2xl text-[#153126]">Administrator seats</h2><div className="mt-5 space-y-3">{data?.seats.map(seat => <div key={seat.seat} className="league-panel flex items-center justify-between p-3"><div><p className="font-semibold text-[#153126]">{seat.displayName}</p><p className="mt-1 text-xs text-slate-500">{seat.userId ? "Account linked" : "Awaiting secure sign-in and assignment"}</p></div><Badge variant="outline">{seat.seat}</Badge></div>)}</div>{currentSeat === "owner" && <div className="mt-5 border-t border-[#1B4332]/10 pt-5"><p className="text-sm font-semibold text-[#153126]">Assign Arish’s seat</p><div className="mt-2 flex gap-2"><select value={arishUserId} onChange={event => setArishUserId(event.target.value)} className="h-10 min-w-0 flex-1 rounded-md border border-[#1B4332]/15 bg-white px-3 text-sm"><option value="">Choose a signed-in account</option>{data?.accounts.map(account => <option key={account.id} value={account.id}>{account.name ?? account.email ?? `Account ${account.id}`}</option>)}</select><Button onClick={() => assignSeat.mutate({ seat: "arish", userId: Number(arishUserId) })} disabled={!arishUserId || assignSeat.isPending}>Assign</Button></div></div>}<p className="mt-5 text-sm leading-6 text-slate-500">New member accounts appear after their first secure sign-in. Use the account-link control below to attach them to a league member record.</p></article></section>
      <section className="league-card p-6"><p className="text-[11px] font-bold uppercase tracking-[0.19em] text-[#C2871F]">Profile linking</p><h2 className="mt-1 font-display text-2xl text-[#153126]">Link a secure account to a league member</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">A signed-in account cannot view league data until it is attached to its exact UBSR member record. This prevents account sharing and determines each person’s team-room access.</p><div className="mt-5 grid gap-3 lg:grid-cols-[1fr_1fr_auto]"><select value={accountForLink} onChange={event => setAccountForLink(event.target.value)} className="h-10 rounded-md border border-[#1B4332]/15 bg-white px-3 text-sm"><option value="">Choose signed-in account</option>{data?.accounts.map(account => <option key={account.id} value={account.id}>{account.name ?? account.email ?? `Account ${account.id}`}</option>)}</select><select value={memberForLink} onChange={event => setMemberForLink(event.target.value)} className="h-10 rounded-md border border-[#1B4332]/15 bg-white px-3 text-sm"><option value="">Choose UBSR member</option>{data?.directory.map(member => <option key={member.memberId} value={member.memberId}>{member.fullName} · {member.memberCode}</option>)}</select><Button onClick={() => linkAccount.mutate({ userId: Number(accountForLink), memberId: Number(memberForLink) })} disabled={!accountForLink || !memberForLink || linkAccount.isPending} className="bg-[#1B4332] hover:bg-[#153126]">Link profile</Button></div></section>
      <section className="grid gap-5 xl:grid-cols-2"><article className="league-card p-6"><p className="text-[11px] font-bold uppercase tracking-[0.19em] text-[#C2871F]">Auction entry</p><h2 className="mt-1 font-display text-2xl text-[#153126]">Record an auction outcome</h2><div className="mt-5 grid gap-3"><select value={auctionPlayerId} onChange={event => setAuctionPlayerId(event.target.value)} className="h-10 rounded-md border border-[#1B4332]/15 bg-white px-3 text-sm"><option value="">Choose a league player</option>{playerRows.map(player => <option key={player.memberId} value={player.memberId}>{player.fullName} · {player.memberCode} · {formatPoints(player.basePrice)}</option>)}</select><select value={auctionStatus} onChange={event => setAuctionStatus(event.target.value)} className="h-10 rounded-md border border-[#1B4332]/15 bg-white px-3 text-sm"><option value="auction_in_progress">Auction in progress</option><option value="sold">Sold</option><option value="unsold">Unsold</option><option value="not_called">Not called</option><option value="unassigned">Unassigned</option></select>{auctionStatus === "sold" && <div className="grid gap-3 sm:grid-cols-2"><select value={auctionManagerId} onChange={event => setAuctionManagerId(event.target.value)} className="h-10 rounded-md border border-[#1B4332]/15 bg-white px-3 text-sm"><option value="">Buyer manager</option>{managers.map(manager => <option key={manager.id} value={manager.id}>{manager.teamName}</option>)}</select><Input type="number" min="0" value={auctionPrice} onChange={event => setAuctionPrice(event.target.value)} placeholder="Final bought price" /></div>}<Textarea value={auctionNote} onChange={event => setAuctionNote(event.target.value)} placeholder="Optional committee note" className="min-h-20" /><Button onClick={() => recordAuction.mutate({ playerMemberId: Number(auctionPlayerId), status: auctionStatus as "auction_in_progress" | "sold" | "unsold" | "not_called" | "unassigned", buyerManagerId: auctionStatus === "sold" ? Number(auctionManagerId) : null, finalBoughtPrice: auctionStatus === "sold" ? Number(auctionPrice) : null, note: auctionNote || null })} disabled={!auctionPlayerId || (auctionStatus === "sold" && (!auctionManagerId || !auctionPrice)) || recordAuction.isPending} className="bg-[#1B4332] hover:bg-[#153126]">Save auction record</Button></div></article>
        <article className="league-card p-6"><p className="text-[11px] font-bold uppercase tracking-[0.19em] text-[#C2871F]">Fixture entry</p><h2 className="mt-1 font-display text-2xl text-[#153126]">Add a league fixture</h2><div className="mt-5 grid gap-3"><select value={homeManagerId} onChange={event => setHomeManagerId(event.target.value)} className="h-10 rounded-md border border-[#1B4332]/15 bg-white px-3 text-sm"><option value="">Home team</option>{managers.map(manager => <option key={manager.id} value={manager.id}>{manager.teamName}</option>)}</select><select value={awayManagerId} onChange={event => setAwayManagerId(event.target.value)} className="h-10 rounded-md border border-[#1B4332]/15 bg-white px-3 text-sm"><option value="">Away team</option>{managers.map(manager => <option key={manager.id} value={manager.id}>{manager.teamName}</option>)}</select><Input type="datetime-local" value={fixtureDate} onChange={event => setFixtureDate(event.target.value)} /><Input value={venue} onChange={event => setVenue(event.target.value)} placeholder="Venue (optional)" /><Button onClick={() => saveFixture.mutate({ homeManagerId: Number(homeManagerId), awayManagerId: Number(awayManagerId), scheduledFor: fixtureDate ? new Date(fixtureDate) : null, venue: venue || null, status: "scheduled" })} disabled={!homeManagerId || !awayManagerId || homeManagerId === awayManagerId || saveFixture.isPending} className="bg-[#1B4332] hover:bg-[#153126]">Save fixture</Button></div></article></section>
      <section className="grid gap-5 xl:grid-cols-2"><article className="league-card p-6"><p className="text-[11px] font-bold uppercase tracking-[0.19em] text-[#C2871F]">Roster correction</p><h2 className="mt-1 font-display text-2xl text-[#153126]">Reassign player ownership</h2><p className="mt-2 text-sm leading-6 text-slate-600">Use only for committee corrections during the ongoing auction. The player remains owned throughout the update and both manager balances are recalculated.</p><div className="mt-5 grid gap-3"><select value={rosterPlayerId} onChange={event => setRosterPlayerId(event.target.value)} className="h-10 rounded-md border border-[#1B4332]/15 bg-white px-3 text-sm"><option value="">Choose rostered player</option>{rosteredPlayers.map(player => <option key={player.memberId} value={player.memberId}>{player.fullName} · {player.teamName}</option>)}</select><select value={reassignmentManagerId} onChange={event => setReassignmentManagerId(event.target.value)} className="h-10 rounded-md border border-[#1B4332]/15 bg-white px-3 text-sm"><option value="">Assign to manager</option>{managers.map(manager => <option key={manager.id} value={manager.id}>{manager.teamName}</option>)}</select><Textarea value={rosterReason} onChange={event => setRosterReason(event.target.value)} placeholder="Required reason for this correction" className="min-h-20" /><Button onClick={() => reassignRoster.mutate({ playerMemberId: Number(rosterPlayerId), toManagerId: Number(reassignmentManagerId), reason: rosterReason })} disabled={!rosterPlayerId || !reassignmentManagerId || rosterReason.trim().length < 3 || reassignRoster.isPending} className="bg-[#1B4332] hover:bg-[#153126]">Reassign roster</Button></div></article>
        <article className="league-card p-6"><p className="text-[11px] font-bold uppercase tracking-[0.19em] text-[#C2871F]">Balance correction</p><h2 className="mt-1 font-display text-2xl text-[#153126]">Apply a documented adjustment</h2><p className="mt-2 text-sm leading-6 text-slate-600">Use a positive number to credit and a negative number to deduct. Every adjustment is retained in the ledger with its reason and administrator account.</p><div className="mt-5 grid gap-3"><select value={adjustmentManagerId} onChange={event => setAdjustmentManagerId(event.target.value)} className="h-10 rounded-md border border-[#1B4332]/15 bg-white px-3 text-sm"><option value="">Choose manager</option>{managers.map(manager => <option key={manager.id} value={manager.id}>{manager.teamName}</option>)}</select><Input type="number" value={adjustmentAmount} onChange={event => setAdjustmentAmount(event.target.value)} placeholder="Adjustment in pts (e.g. -50 or 50)" /><Textarea value={adjustmentReason} onChange={event => setAdjustmentReason(event.target.value)} placeholder="Required reason for this adjustment" className="min-h-20" /><Button onClick={() => adjustBalance.mutate({ managerId: Number(adjustmentManagerId), amount: Number(adjustmentAmount), reason: adjustmentReason })} disabled={!adjustmentManagerId || !adjustmentAmount || adjustmentReason.trim().length < 3 || adjustBalance.isPending} className="bg-[#1B4332] hover:bg-[#153126]">Record balance adjustment</Button></div></article></section>
    </>}
  </div></LeagueNav>;
}
