import LeagueNav from "@/components/LeagueNav";
import PageHeader from "@/components/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { formatPoints, statusLabel } from "@/lib/league";
import { Clock3, LockKeyhole, MessageCircle, Send, ShoppingBag } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function Market() {
  const utils = trpc.useUtils();
  const { data: overview } = trpc.league.overview.useQuery();
  const { data: threads = [] } = trpc.chat.publicTradeThreads.useQuery();
  const [playerMemberId, setPlayerMemberId] = useState("");
  const [basePrice, setBasePrice] = useState("");
  const [offerDrafts, setOfferDrafts] = useState<Record<number, string>>({});
  const [messageDrafts, setMessageDrafts] = useState<Record<number, string>>({});
  const createThread = trpc.trading.createThread.useMutation({ onSuccess: () => { toast.success("Listing published."); setPlayerMemberId(""); setBasePrice(""); utils.chat.publicTradeThreads.invalidate(); }, onError: error => toast.error(error.message) });
  const makeOffer = trpc.trading.makeOffer.useMutation({ onSuccess: () => { toast.success("Offer submitted."); utils.chat.publicTradeThreads.invalidate(); }, onError: error => toast.error(error.message) });
  const resolveOffer = trpc.trading.resolveOffer.useMutation({ onSuccess: () => { toast.success("Offer resolved."); utils.chat.publicTradeThreads.invalidate(); utils.league.overview.invalidate(); }, onError: error => toast.error(error.message) });
  const postMessage = trpc.chat.postPublicTradeMessage.useMutation({ onSuccess: () => { utils.chat.publicTradeThreads.invalidate(); }, onError: error => toast.error(error.message) });
  const marketOpen = overview?.summary.market.isOpen;
  const managerId = overview?.identity.managerId;
  const roster = overview?.dashboard.roster ?? [];

  return <LeagueNav><div className="mx-auto max-w-6xl space-y-7"><PageHeader eyebrow="Controlled exchange" title="Transfer market" description="All threads are public. Managers set a base price, receive bids or negotiation notes, and manually accept or reject each exchange. There is no automated execution schedule." />
    {!marketOpen ? <div className="league-card overflow-hidden"><div className="bg-[#153126] p-7 text-white"><div className="flex items-start gap-4"><div className="grid size-11 place-items-center rounded-xl bg-[#E0A02C]/20"><LockKeyhole className="size-5 text-[#E0A02C]" /></div><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#E0A02C]">Market safeguard</p><h2 className="mt-2 font-display text-3xl">Transfer market is closed.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/75">It opens only after both administrator seats independently approve it. No public listing, bid, negotiation, or ownership change can be created while this safeguard is active.</p></div></div></div></div> : <>
      {managerId && <section className="league-card p-6"><p className="text-[11px] font-bold uppercase tracking-[0.2em] text-[#C2871F]">Manager action</p><h2 className="mt-1 font-display text-2xl text-[#153126]">List one of your rostered players</h2><div className="mt-5 grid gap-3 md:grid-cols-[1fr_180px_auto]"><select value={playerMemberId} onChange={event => setPlayerMemberId(event.target.value)} className="h-10 rounded-md border border-[#1B4332]/15 bg-white px-3 text-sm"><option value="">Choose a player</option>{roster.map(player => <option key={player.memberId} value={player.memberId}>{player.fullName} · {player.memberCode}</option>)}</select><Input value={basePrice} onChange={event => setBasePrice(event.target.value)} type="number" min="1" placeholder="Base price (pts)" /><Button onClick={() => createThread.mutate({ playerMemberId: Number(playerMemberId), basePrice: Number(basePrice) })} disabled={!playerMemberId || !basePrice || createThread.isPending} className="bg-[#1B4332] hover:bg-[#153126]">Publish listing</Button></div></section>}
      <section className="space-y-5">{threads.length ? threads.map(thread => <article key={thread.id} className="league-card overflow-hidden"><div className="flex flex-col justify-between gap-4 border-b border-[#1B4332]/10 bg-[#FBFBF8] px-6 py-5 md:flex-row md:items-center"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[#C2871F]">Public listing · {thread.playerCode}</p><h2 className="mt-1 font-display text-2xl text-[#153126]">{thread.playerName}</h2><p className="mt-1 text-sm text-slate-500">Seller: {thread.sellerTeamName} · Base {formatPoints(thread.basePrice)}</p></div><Badge variant="outline" className="border-[#1B4332]/15 bg-white text-[#153126]">{statusLabel(thread.status)}</Badge></div>
        <div className="grid gap-5 p-6 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-500">Offers</p><div className="mt-3 space-y-3">{thread.offers.length ? thread.offers.map(offer => <div key={offer.id} className="league-panel p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-semibold text-[#153126]">{offer.buyerTeamName}</p><p className="mt-1 font-mono text-xs text-slate-600">{formatPoints(offer.bidPoints)}</p></div><Badge variant="outline" className="text-[10px]">{statusLabel(offer.status)}</Badge></div>{offer.negotiationNote && <p className="mt-2 text-sm leading-5 text-slate-600">{offer.negotiationNote}</p>}{managerId === thread.sellerManagerId && offer.status === "open" && <div className="mt-3 flex gap-2"><Button size="sm" onClick={() => resolveOffer.mutate({ offerId: offer.id, accept: true })} className="bg-[#1B4332] hover:bg-[#153126]">Accept</Button><Button size="sm" variant="outline" onClick={() => resolveOffer.mutate({ offerId: offer.id, accept: false })}>Reject</Button></div>}</div>) : <p className="py-3 text-sm text-slate-500">No bids placed yet.</p>}</div>{managerId && managerId !== thread.sellerManagerId && thread.status === "open" && <div className="mt-4 flex gap-2"><Input type="number" min="1" value={offerDrafts[thread.id] ?? ""} onChange={event => setOfferDrafts(current => ({ ...current, [thread.id]: event.target.value }))} placeholder="Bid in pts" /><Button onClick={() => makeOffer.mutate({ threadId: thread.id, bidPoints: Number(offerDrafts[thread.id]) })} disabled={!offerDrafts[thread.id]}>Bid</Button></div>}</div>
          <div><p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-500">Public negotiation</p><div className="mt-3 max-h-52 space-y-3 overflow-auto rounded-xl border border-[#1B4332]/10 bg-[#F9FAF7] p-4">{thread.messages.length ? thread.messages.map(message => <div key={message.id}><p className="text-xs font-semibold text-[#153126]">{message.authorName ?? "League member"}</p><p className="mt-1 text-sm leading-5 text-slate-600">{message.body}</p></div>) : <p className="text-sm text-slate-500">Public discussion starts here when the first message is posted.</p>}</div><div className="mt-3 flex gap-2"><Textarea value={messageDrafts[thread.id] ?? ""} onChange={event => setMessageDrafts(current => ({ ...current, [thread.id]: event.target.value }))} placeholder="Post a public negotiation message" className="min-h-10 resize-none" /><Button size="icon" onClick={() => postMessage.mutate({ threadId: thread.id, body: messageDrafts[thread.id] })} disabled={!messageDrafts[thread.id]}><Send className="size-4" /></Button></div><div className="mt-5 border-t border-[#1B4332]/10 pt-4"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-slate-500"><Clock3 className="size-3.5" /> Audited history</p><div className="mt-3 space-y-2">{thread.events.length ? thread.events.map(event => <div key={event.id} className="text-xs leading-5 text-slate-600"><span className="font-semibold text-[#153126]">{statusLabel(event.action)}</span>{event.detail ? ` — ${event.detail}` : ""}</div>) : <p className="text-xs text-slate-500">The first action on this listing will be recorded here.</p>}</div></div></div></div>
      </article>) : <div className="league-card grid min-h-64 place-items-center p-8 text-center"><div><ShoppingBag className="mx-auto size-7 text-[#1B4332]" /><h2 className="mt-4 font-display text-2xl text-[#153126]">No public listings yet.</h2><p className="mt-2 text-sm text-slate-500">The market is open, but no manager has listed a player for negotiation.</p></div></div>}</section>
    </>}
  </div></LeagueNav>;
}
